'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Comment_Generator.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #student has been having trouble with the course. With a mark of #grade% in this course, lots of improvements need to be made. Good luck in the future.
        '''#student has been struggling to keep up with their class in terms of their grade. Passing with a score of #grade% in this course is a worrying trend and should be looked further into. Good luck next term.
        '''#student has passed this course with a #grade%! Although #student passed, I suggest reviewing materials again for a better understanding. I wish #student [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property almostFailComments() As String
            Get
                Return ResourceManager.GetString("almostFailComments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #student has had ups and downs in this course but has managed to prevail and end up with a good mark of #grade%. It has been a pleasure teaching #student this semester.
        '''#student has made huge improvements in this course and should be proud of their great score of #grade%. I look forward to teaching you again next semester!
        '''#student has had a good time throughout the course. Passing with a #grade%, #student shows good knowledge of subjects. Good luck next semester.
        '''#student has had ups and downs in this c [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property almostSuccessComments() As String
            Get
                Return ResourceManager.GetString("almostSuccessComments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ---distracting---
        '''#student easily gets distracted during class.
        '''#student doesn&apos;t show effort towards the course and distracts others.
        '''#student has trouble concentrating on their work and is distracting to others.
        '''#student has concentration issues in class which should be worked on.
        '''---end distracting---
        '''---seekHelp---
        '''#student has trouble with assignments and should seek help when needed.
        '''#student needs to talk with myself or look towards Peer Tutoring for help in understanding concepts covered in c [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property criticisms() As String
            Get
                Return ResourceManager.GetString("criticisms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #student is failing the course with a #grade%. I suggest #student to seek help from either myself or other students to understand the concepts and pass the course. This grade is dissappointing and I&apos;m sure the #student can do better.
        '''#student, you had a hard time during this course. #student demonstrates an unwillingness to extend or challenge themselves to acheive success in this course leading to the failing mark of #grade%. I recommend #student to ask for help when needed.
        '''#student, this course has sho [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property failComments() As String
            Get
                Return ResourceManager.GetString("failComments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property itextsharp() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("itextsharp", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property itextsharp_pdfa() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("itextsharp_pdfa", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property itextsharp_xtra() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("itextsharp_xtra", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property levelThree() As String
            Get
                Return ResourceManager.GetString("levelThree", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #student is having trouble adjusting to this course..
        '''</summary>
        Friend ReadOnly Property levelTwo() As String
            Get
                Return ResourceManager.GetString("levelTwo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ---improving---
        '''#student is readily improving in the course.
        '''#student now is learning to accept responsibility towards his assignments which is a great sign of improvement.
        '''#student is developing the skills to pass this course in a fast pace which is a really good sign.
        '''#student is showing an improvement in the work habits and is learning to listen to directions more carefully.
        '''---end improving---
        '''---good understanding---
        '''#student is a good worker and shows full determination towards the schoolwork.        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property praises() As String
            Get
                Return ResourceManager.GetString("praises", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ---1---
        '''#student, you have had a successful run in this course! You have strong study habits, which are reflected in your high grade of #grade%. I&apos;ve seen good critical thinking abilities and great problem solving skills from you. Throughout this course, you were determined to understand everything and did not give up until mastering the concept. It has been a pleasure teaching you this year and I wish you the best of luck for the future.
        '''#student, you have had a successful run in this course! You have st [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property rephrasedSuccess() As String
            Get
                Return ResourceManager.GetString("rephrasedSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #student, you have had a successful run in this course! You have strong study habits, which are reflected in your high grade of #grade%. I&apos;ve seen good critical thinking abilities and great problem solving skills from you. Throughout this course, you were determined to understand everything and did not give up until mastering the concept. It has been a pleasure teaching you this year and I wish you the best of luck for the future.
        '''#student, I have observed in class that you have all the study habits of a h [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property successComments() As String
            Get
                Return ResourceManager.GetString("successComments", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
